version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=32741755eE@@
      - MYSQL_DATABASE=CinemaAPIDatabase
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=CinemaAPIDatabase;User=root;Password=32741755eE@@;

volumes:
  mysql-data:
